### ISSUE TITLE
Movie / Shows / Music library completely empty, even after sync/refresh

### ISSUE THREAD

**Issue by LeVraiRoiDHyrule** [jellyfin/jellyfin-kodi#516]
**Describe the bug**

I recently switched to Kodi 19, and I re-installed the Jellyfin for Kodi addon.
I can correctly connect to my Jellyfin server. At each boot, the welcome notification appears.
But when I try to sync the library, it loads for around 5minutes like it should do, but after, every Kodi library is still empty.
I tried multiple times, still the same.

I have to precise that my Kodi is a multi-user setup, so I have the Jellyfin for Kodi addon installed for each of my 3 profiles, but each linked to a different Jellyfin account. But that doesn't seem to be the source of the problem, as it is the same with a single profile setup.

I am on an Odroid N2+, **but that also doesn't seem to be the issue as I have the exact same problem with official Kodi 19 on my PC.**

**To Reproduce**

1. Install Kodi 19 (CoreElec) on Odroid N2+ (or PC)
2. Install Jellyfin for Kodi addon
3. Try to sync your libraries

**Expected behavior**

My jellyfin libraries should by synced to the Kodi librairies

**Logs**

https://1drv.ms/u/s!AhNGmCtr4NeUpKE0mXeEkSwNJi3HAA?e=IrnI89
(too long for pastebin, sorry)

**Screenshots**

![IMG_20210506_000037_tigr](https://user-images.githubusercontent.com/64923542/117215373-66a01e00-adfe-11eb-8581-a434db9d92ed.jpg)

![IMG_20210506_000053_tigr](https://user-images.githubusercontent.com/64923542/117215356-5e47e300-adfe-11eb-85ac-3dde4b3750b0.jpg)

**System (please complete the following information):**
 - OS: CoreElec
 - Jellyfin Version: 10.7.5
 - Kodi Version: 19.0
 - Addon Version: 0.7.2+py3
 - Playback Mode: Add-on
 
**Additional context**

**Comment by mcarlton00** [comment]
Sounds like a duplicate of #445, but I didn't think that was breaking sync.  And I haven't managed to replicate it myself yet.

As an aside, what happens if you try to sync only shows or music?  Judging by your logs, it's only the movies library that's failing, but it's probably trying to do Movies first and never reaching those other libraries.

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> Sounds like a duplicate of #445, but I didn't think that was breaking sync. And I haven't managed to replicate it myself yet.
> 
> As an aside, what happens if you try to sync only shows or music? Judging by your logs, it's only the movies library that's failing, but it's probably trying to do Movies first and never reaching those other libraries.

I have exactly the same behavior for all my librairies, even if I try to refresh only the Shows.
The initial sync after installing loads but at the end everything is empty.
If I try to manually refresh after in the same session (without rebooting), it's the same behaviour.
If I try to manually refresh after a reboot, I get a "something went wrong during the sync".

The problem seems very global. I strictly never managed to get the addon working with Kodi 19, both on my PC, friend's PCs, my phone, my Xbox, my Odroid...  but on Kodi 18 no problem. But I would like to update to the newest kodi if possible.

**Comment by mcarlton00** [comment]
Can you try downgrading to version 0.7.1 of the addon and seeing if that has a difference?  Ideally by doing a database reset instead of just syncing a library from the addon menu.  There are some sync issues in 0.7.2.  I'm not seeing evidence of those in your logs, but it's possible I'm overlooking them.  They should be fixed in 0.7.3 but it hasn't been released yet.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I just tried downgrading to 0.7.1, did a full database reset, and synced again. It's the same behavior as it 0.7.2.

**Comment by LeVraiRoiDHyrule** [comment]
Hi, if it can help, I got more logs from Kodi https://1drv.ms/u/s!AhNGmCtr4NeUpKE8IO-FGFNn2VuW9Q?e=BSTURg
This one is with the version 0.7.1, I tried a resync. Music is correctly synced, and it plays, but movies and shows are not synced to the library.

**Comment by mcarlton00** [comment]
Debug logging from Kodi isn't helping in this case.  It's simply too much noise to sort through and isn't providing any helpful information.  Enabling it on the Jellyfin addon would be more helpful `Addons -> Jellyfin -> Settings -> Advanced -> Log level`

However, regardless of what the log level is set to, this doesn't make any sense. There are no errors in regards to the sync outside of that trailers one, and that isn't a cause for sync failure.  Do you have shell access on this box?  It may be helpful to check if it's possible it's loading the wrong database, though this also shouldn't be possible.

**Comment by LeVraiRoiDHyrule** [comment]
I'll try resyncing with the addon log level to debug, and I'll send it to you.

Yes, I have complete shell access on my machine. What do you want me to check ?

**Comment by LeVraiRoiDHyrule** [comment]
Here my new log with Jellyfin addon log level to Debug. I completely reset the Kodi library, reinstalled the addon and deleting all the settings, then connected it again and did the initial sync

https://1drv.ms/u/s!AhNGmCtr4NeUpKFDkgM5cNzdqKRgRw?e=Uqwylr

**Comment by mcarlton00** [comment]
It does say it's using the correct database file, as far as I can tell.

> INFO::jellyfin_kodi/database/__init__.py:153 Database locked in: /storage/.kodi/userdata/profiles/Valentin/Database/MyVideos119.db

So that rules out one idea of what's going on.

Next idea is that it's running a clean library, but I don't see that being triggered anywhere in your logs, so that also seems unlikely.

I suppose the next thing is to check the database directly and see if it's been populated.  From the shell on your coreelec box, try this:

```
sqlite3 /storage/.kodi/userdata/profiles/Valentin/Database/MyVideos119.db <<EOF
select * from movie;
EOF
```

And see if you get any output.  It should be very obvious.

**Comment by LeVraiRoiDHyrule** [comment]
If it can help, here is a new log. This one is still with Jellyfin addon debug log, but this time it's what happens when I restarted the card, so with the initial sync already done (without error but with empty librairies at the end), I tried syncing again from the addon (that's where I get the "something went wrong during the sync" that is on my 1st capture of the original post).

https://1drv.ms/u/s!AhNGmCtr4NeUpKFEubB5LVijLhCMsQ?e=RRep11

**Comment by mcarlton00** [comment]
The errors shown in this most recent logs look to be from from #511 which was fixed with the release of 0.7.3 earlier today.

However, there's something else going on here.  The fact that the database is indeed being populated, but then isn't showing in the UI indicates that there's become a sort of disconnect between the kodi profiles and the database that it's using.  The only thing I can think of is if the profiles were set up to use a shared database, so then the database in your Valentin isn't actually valid for that profile.  This is just a guess at this point, as I haven't been able to replicate this behavior.  All indications in the logs (except where you expressly get the error popup, which should be fixed now) are saying that the syncs have completed successfully.  With the debug logging we've seen each entry going into the database.  You can read the database manually and the correct things seem to be there.  Especially since we've gotten music to work but not videos.

![sense](https://user-images.githubusercontent.com/17029228/117557627-f504e180-b042-11eb-8adf-e04a69b109ad.gif)

I really hate pulling the "not our problem" card, but as the man says, nothing here is making any sense.  I have to assume it's something in the kodi profiles themselves that aren't set up correctly, but I've never seen it before.  There's always the nuclear option of erasing the entire `/storage/.kodi` directory and starting from a totally blank slate, but especially if you have multiple profiles or addons that's kinda an annoying step.

**Comment by LeVraiRoiDHyrule** [comment]
Hi,

I just tried the version 0.7.3 of the addon.
On the Odroid N2, I fully re-flashed the eMMC and re-installed the addon and everything. It doesn't change the issue, I still have the music working but the rest of the movies and series are not synced. Librairies are still empty.

On my PC, it's different. Now, everything syncs correctly. All my movies and series are now appearing in the library, both with a single profile and a multi-profile setup. But I'm having issues for playing something. If I try to play something, it plays for 5-6 seconds then Kodi completely freezes. I looked at the logs, and I'm having this error :

ERROR <general>: Got MSGQ_ABORT or MSGO_IS_ERROR return true

**Comment by LeVraiRoiDHyrule** [comment]
Hi, I have some news.

With the version 0.7.3 of the addon, it seems to work when my setup is using a single profile ! It works on both PC and Odroid.

I still have the same issue where only music is synced when using multiple profile. (always with "Media info" and "Media sources" set to "Separated" when creating a new profile)

**Comment by mcarlton00** [comment]
That had occurred to me, but I can't replicate it.  The master profile is empty, and I have 2 profiles (matt and testuser).  Both of them have different combinations of music/video libraries synced.  Both of them synced with no problems, and both profiles have populated libraries.

That's not saying it's flawless.  In my profiles, playback seems to be silently failing for no reason, and if I try to change profiles Kodi hard crashes.  But that seems like unrelated problems and are possibly Kodi itself.

**Comment by LeVraiRoiDHyrule** [comment]
When you create a new Kodi profile, it first ask you how you want your libraries and sources to be with this new profile (separated or not), but after this it also asks you if you want to copy the settings of the master profile to the new one. Did you choose to do that ? I did, because I have a lot of settings to change that I want to be replicated on all accounts. That could play a role in that

**Comment by LeVraiRoiDHyrule** [comment]
> 
> 
> That had occurred to me, but I can't replicate it. The master profile is empty, and I have 2 profiles (matt and testuser). Both of them have different combinations of music/video libraries synced. Both of them synced with no problems, and both profiles have populated libraries.
> 
> That's not saying it's flawless. In my profiles, playback seems to be silently failing for no reason, and if I try to change profiles Kodi hard crashes. But that seems like unrelated problems and are possibly Kodi itself.

I would have some questions to search a bit more:
- On your master profile, is the addon installed ?
- Same question for the repository
- Are your settings shared between the profiles or not ?
- Did you choose to copy the settings of the master profile to the new ones when creating them ?

If I just create 2 new profiles, without changing any setting, and try to sync one to my server, I still have the same empty librairy issues.

**Comment by LeVraiRoiDHyrule** [comment]
New infos:
I tried with creating new profiles from the start, without changing ANY setting. In general, I begin by changing the hardware keyboard layout (I'm using AZERTY keyboard) and a few other things. This time, I didn't do it. I went straight forward to creating the profiles and connecting to Jellyfin and it worked !!!

**I can now be 100% sure that something in the "few other things" is causing problems with the Jellyfin addon**. I don't know what it could be yet, it's either with languages, keyboard layout, or profile creation (maybe it's linked to profile PIN codes, I'll try with editing all my settings but without locking anything with PIN)

**Comment by LeVraiRoiDHyrule** [comment]
BINGO !!!! I FINALLY FOUND WHAT CAUSES THE ISSUE !!!

**The issue of empty video libraries happens when the master profile is locked with a PIN code.**
Locking the master profile with a PIN code is required if you want to lock other profiles with a code

![IMG_20210512_202128_tigr](https://user-images.githubusercontent.com/64923542/118025236-e29ae880-b35f-11eb-8779-e36f3cf598d2.jpg)

I can now have a fully working multi-profile Kodi setup, as long as I don't lock any of my profiles with a PIN code.

I think the issue could easily be replicated on your side, because it seems to be very global (happens on all my devices, Odroid, PC, phone..... as I said before). If you are able to replicate it, then I think I can't help further as I'm absolutely not an expert. If you can't replicate it, then don't hesitate to ask more questions if it helps to solve the issue for everyone.

I'm very happy I finally found the cause. It took hours of trying..... but it's finally good.

**Comment by LeVraiRoiDHyrule** [comment]
Ok, I remove what I just said. It's not fully fixed. There is in fact 2 issues:

- Empty librairies -> This one is now solved, it happens when the master profile is locked with a code
- Error of the addon when trying to setup a second profile -> That's the one I just talked about here:

> But, if I try to create another profile and try to sync, exactly the same way as before, this time I get an error:
https://1drv.ms/u/s!AhNGmCtr4NeUpKFqhCjwPf2g9WjUHw?e=fgDigs
(this error is the same for any other profile created, but not the 1st one)

![IMG_20210512_203213_tigr](https://user-images.githubusercontent.com/64923542/118026970-b84a2a80-b361-11eb-8aab-13d8dcdba71a.jpg)

This one is still not solved. It happens only for the 2nd profile I try to setup. My master profile is empty, and I've got a 1st additionnal profile that is correctly set up with Jellyfin. The second one throws the error above. Here is an additionnal log if needed:

https://1drv.ms/u/s!AhNGmCtr4NeUpKFuoJLzrq84b5TtCw?e=fTjWxG

**Comment by LeVraiRoiDHyrule** [comment]
CAUSE OF THE 2ND BUG FOUND !!

**The addon error happens after installing, if the name of profile contains special symbols** (in my case, french accents like é or è)

Now I can say I finally found the cause of all my problems. Don't hesitate if you have questions or need more log data

**Comment by mcarlton00** [comment]
In that case, it sounds like this is going to get everybody's favorite label

**Comment by LeVraiRoiDHyrule** [comment]
Thanks ! And yes, issue 1 with the master lock is a duplicate of #169 , you're right. I hope the logs I sent can help solve it as well. Have a great day, and thanks for your awesome work ! I use your addon nearly every day and I love it.
